// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeBox: typeof import('./theme/components/CodeBox.vue')['default']
    CodeGroupItem: typeof import('./theme/components/CodeGroupItem.vue')['default']
    HomePage: typeof import('./theme/components/HomePage.vue')['default']
    Response: typeof import('./theme/components/Response.vue')['default']
    SelectLibraries: typeof import('./theme/components/SelectLibraries.vue')['default']
    Tooltip: typeof import('./theme/components/shared/Tooltip.vue')['default']
  }
}
