import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"czg","titleTemplate":"Interactive Commitizen CLI that generate standardized commit messages","description":"Interactive Commitizen CLI that generate standardized commit messages","frontmatter":{"title":"czg","titleTemplate":"Interactive Commitizen CLI that generate standardized commit messages","description":"Interactive Commitizen CLI that generate standardized commit messages","layout":"doc"},"headers":[{"level":2,"title":"Quick start","slug":"quick-start","link":"#quick-start","children":[]},{"level":2,"title":"Features and Help","slug":"features-and-help","link":"#features-and-help","children":[]},{"level":2,"title":"Projects using czg CLI","slug":"projects-using-czg-cli","link":"#projects-using-czg-cli","children":[]},{"level":2,"title":"LICENSE","slug":"license","link":"#license","children":[]}],"relativePath":"en/api/index.md","lastUpdated":1676281064000}');
const _sfc_main = { name: "en/api/index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 class="clip">Focus on Matters, Your Business</h1><p class="description">Interactive Commitizen CLI that generate standardized commit messages</p><p align="center"><a target="_blank" href="https://github.com/Zhengqbbb/cz-git"><img style="${ssrRenderStyle({ "display": "inline-block", "margin": "0.2em" })}" alt="GitHub Repo stars" src="https://img.shields.io/github/stars/zhengqbbb/cz-git?style=social"></a><a target="_blank" href="https://github.com/agarrharr/awesome-cli-apps#git"><img style="${ssrRenderStyle({ "display": "inline-block", "margin": "0.2em" })}" alt="awesome-cli-app" src="https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg"></a><br><a href="https://www.npmjs.com/package/czg"><img style="${ssrRenderStyle({ "display": "inline-block", "margin": "0.2em" })}" alt="npm" src="https://img.shields.io/npm/v/czg?style=flat-square&amp;logo=npm"></a><a href="https://formulae.brew.sh/formula/czg"><img style="${ssrRenderStyle({ "display": "inline-block", "margin": "0.2em" })}" alt="homebrew" src="https://img.shields.io/homebrew/v/czg?style=flat-square&amp;logo=homebrew&amp;label=homebrew"></a></p><br><ul><li>⚡️ <strong>Lightweight</strong> : Zero Dependencies (1.3MB)</li><li>🤗 <strong>Simpler and Faster</strong> : No plugin, No adapter, No extra steps, You can use <code>npx</code> | <code>npm script</code> | <code>global install</code>... quick start CLI in your any project</li><li>😎 <strong>Highly Customizable</strong> : Internally contains the core of cz-git. Extend all the features of cz-git. Same behavior, Same configuration loader... You can customize the commit CLI according to your need</li></ul><p><img src="https://user-images.githubusercontent.com/40693636/175753060-cf4f5e48-100d-430a-93e9-31b17f42802f.gif" alt="demo-gif" width="688" height="264" loading="lazy" decoding="async" onerror="this.classList.add(&#39;error&#39;);"></p><h2 id="quick-start" tabindex="-1">Quick start <a class="header-anchor" href="#quick-start" aria-hidden="true">#</a></h2><ol><li>Now try it out, use <code>npx czg</code> in <strong>your any projects</strong></li><li>And then, let&#39;s try to simply configure it. Create a <code>.czrc</code> file in the project root directory</li></ol><div class="language-json"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki vitesse-dark vp-code-dark" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#666666" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">  </span><span style="${ssrRenderStyle({ "color": "#C98A7D99" })}">&quot;</span><span style="${ssrRenderStyle({ "color": "#B8A965" })}">scopes</span><span style="${ssrRenderStyle({ "color": "#C98A7D99" })}">&quot;</span><span style="${ssrRenderStyle({ "color": "#666666" })}">:</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#666666" })}">[</span><span style="${ssrRenderStyle({ "color": "#C98A7D99" })}">&quot;</span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">hello</span><span style="${ssrRenderStyle({ "color": "#C98A7D99" })}">&quot;</span><span style="${ssrRenderStyle({ "color": "#666666" })}">,</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D99" })}">&quot;</span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">world</span><span style="${ssrRenderStyle({ "color": "#C98A7D99" })}">&quot;</span><span style="${ssrRenderStyle({ "color": "#666666" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#666666" })}">}</span></span>
<span class="line"></span></code></pre><pre class="shiki vitesse-light vp-code-light" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#999999" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">  </span><span style="${ssrRenderStyle({ "color": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "color": "#998418" })}">scopes</span><span style="${ssrRenderStyle({ "color": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "color": "#999999" })}">:</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#999999" })}">[</span><span style="${ssrRenderStyle({ "color": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "color": "#B56959" })}">hello</span><span style="${ssrRenderStyle({ "color": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "color": "#999999" })}">,</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "color": "#B56959" })}">world</span><span style="${ssrRenderStyle({ "color": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "color": "#999999" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#999999" })}">}</span></span>
<span class="line"></span></code></pre></div><div class="tip custom-block"><p class="custom-block-title">TIP</p><p>More information about configure file and options. See → <a href="/config/">Config</a></p></div><h2 id="features-and-help" tabindex="-1">Features and Help <a class="header-anchor" href="#features-and-help" aria-hidden="true">#</a></h2><div class="language-sh"><button title="Copy Code" class="copy"></button><span class="lang">sh</span><pre class="shiki vitesse-dark vp-code-dark" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#80A665" })}">$</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">czg</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C99076" })}">--help</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#80A665" })}">NAME:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">czg</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">-</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">Interactive</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">Commitizen</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">CLI</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">that</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">generate</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">standardized</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">commit</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">messages</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#80A665" })}">WEBSITE:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">https://cz-git.qbb.sh/cli/</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">https://github.com/Zhengqbbb/cz-git</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#80A665" })}">SYNOPSIS:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">czg</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#666666" })}">[</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">subcommand...</span><span style="${ssrRenderStyle({ "color": "#666666" })}">]</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#666666" })}">[</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">options...</span><span style="${ssrRenderStyle({ "color": "#666666" })}">]</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#666666" })}">[</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">git-commit-options...</span><span style="${ssrRenderStyle({ "color": "#666666" })}">]</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#80A665" })}">SUBCOMMAND:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#4D9375" })}">break</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">          </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">Turn</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">on</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">appends</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">a</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">!</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">after</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">the</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">type/scope</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">emoji</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">          </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">Turn</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">on</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">output</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">message</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">with</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">emoji</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">mode</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">checkbox</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">       </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">Turn</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">on</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">scope</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">checkbox</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">mode</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">gpg</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">            </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">Turn</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">on</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">use</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">GPG</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">sign</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">commit</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">message</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#80A665" })}">OPTIONS:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">--config</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">       </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">Specify</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">the</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">configuration</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">file</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">to</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">use</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#B8A965" })}">:</span><span style="${ssrRenderStyle({ "color": "#80A665" })}">,</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C99076" })}">--alias</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">     </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">Directly</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">submit</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">the</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">defined</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">commit</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">message</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">-r,</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C99076" })}">--retry</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">Directly</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">retry</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">submit</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">by</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">the</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">last</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">message</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">-h,</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C99076" })}">--help</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">     </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">Show</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">help</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">-v,</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C99076" })}">--version</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">  </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">Show</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">version</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#80A665" })}">EXAMPLES:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">czg</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">czg</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">emoji</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">czg</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">:fd</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">czg</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C99076" })}">--alias=fd</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}">    </span><span style="${ssrRenderStyle({ "color": "#80A665" })}">czg</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C99076" })}">--config=</span><span style="${ssrRenderStyle({ "color": "#C98A7D99" })}">&quot;</span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">./config/cz.json</span><span style="${ssrRenderStyle({ "color": "#C98A7D99" })}">&quot;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#80A665" })}">Extends</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D99" })}">&#39;</span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">git commit</span><span style="${ssrRenderStyle({ "color": "#C98A7D99" })}">&#39;</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">options.</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#80A665" })}">See</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D99" })}">&#39;</span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">git commit --help</span><span style="${ssrRenderStyle({ "color": "#C98A7D99" })}">&#39;</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">for</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">more</span><span style="${ssrRenderStyle({ "color": "#DBD7CAEE" })}"> </span><span style="${ssrRenderStyle({ "color": "#C98A7D" })}">information.</span></span>
<span class="line"></span></code></pre><pre class="shiki vitesse-light vp-code-light" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#59873A" })}">$</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">czg</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#A65E2B" })}">--help</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#59873A" })}">NAME:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">czg</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">-</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">Interactive</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">Commitizen</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">CLI</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">that</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">generate</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">standardized</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">commit</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">messages</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#59873A" })}">WEBSITE:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">https://cz-git.qbb.sh/cli/</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">https://github.com/Zhengqbbb/cz-git</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#59873A" })}">SYNOPSIS:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">czg</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#999999" })}">[</span><span style="${ssrRenderStyle({ "color": "#393A34" })}">subcommand...</span><span style="${ssrRenderStyle({ "color": "#999999" })}">]</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#999999" })}">[</span><span style="${ssrRenderStyle({ "color": "#393A34" })}">options...</span><span style="${ssrRenderStyle({ "color": "#999999" })}">]</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#999999" })}">[</span><span style="${ssrRenderStyle({ "color": "#393A34" })}">git-commit-options...</span><span style="${ssrRenderStyle({ "color": "#999999" })}">]</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#59873A" })}">SUBCOMMAND:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#1E754F" })}">break</span><span style="${ssrRenderStyle({ "color": "#393A34" })}">          </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">Turn</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">on</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">appends</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">a</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">!</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">after</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">the</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">type/scope</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">emoji</span><span style="${ssrRenderStyle({ "color": "#393A34" })}">          </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">Turn</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">on</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">output</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">message</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">with</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">emoji</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">mode</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">checkbox</span><span style="${ssrRenderStyle({ "color": "#393A34" })}">       </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">Turn</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">on</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">scope</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">checkbox</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">mode</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">gpg</span><span style="${ssrRenderStyle({ "color": "#393A34" })}">            </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">Turn</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">on</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">use</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">GPG</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">sign</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">commit</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">message</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#59873A" })}">OPTIONS:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">--config</span><span style="${ssrRenderStyle({ "color": "#393A34" })}">       </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">Specify</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">the</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">configuration</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">file</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">to</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">use</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#998418" })}">:</span><span style="${ssrRenderStyle({ "color": "#59873A" })}">,</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#A65E2B" })}">--alias</span><span style="${ssrRenderStyle({ "color": "#393A34" })}">     </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">Directly</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">submit</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">the</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">defined</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">commit</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">message</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">-r,</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#A65E2B" })}">--retry</span><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">Directly</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">retry</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">submit</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">by</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">the</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">last</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">message</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">-h,</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#A65E2B" })}">--help</span><span style="${ssrRenderStyle({ "color": "#393A34" })}">     </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">Show</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">help</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">-v,</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#A65E2B" })}">--version</span><span style="${ssrRenderStyle({ "color": "#393A34" })}">  </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">Show</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">version</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#59873A" })}">EXAMPLES:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">czg</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">czg</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">emoji</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">czg</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">:fd</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">czg</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#A65E2B" })}">--alias=fd</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#393A34" })}">    </span><span style="${ssrRenderStyle({ "color": "#59873A" })}">czg</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#A65E2B" })}">--config=</span><span style="${ssrRenderStyle({ "color": "#B5695999" })}">&quot;</span><span style="${ssrRenderStyle({ "color": "#B56959" })}">./config/cz.json</span><span style="${ssrRenderStyle({ "color": "#B5695999" })}">&quot;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#59873A" })}">Extends</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "color": "#B56959" })}">git commit</span><span style="${ssrRenderStyle({ "color": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">options.</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#59873A" })}">See</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "color": "#B56959" })}">git commit --help</span><span style="${ssrRenderStyle({ "color": "#B5695999" })}">&#39;</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">for</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">more</span><span style="${ssrRenderStyle({ "color": "#393A34" })}"> </span><span style="${ssrRenderStyle({ "color": "#B56959" })}">information.</span></span>
<span class="line"></span></code></pre></div><h2 id="projects-using-czg-cli" tabindex="-1">Projects using czg CLI <a class="header-anchor" href="#projects-using-czg-cli" aria-hidden="true">#</a></h2><table><tr><td align="center" width="200px"><a target="_blank" href="https://github.com/nrwl/nx"><img src="https://user-images.githubusercontent.com/40693636/211251507-e45992b8-6e49-44e4-933c-100a68f5ff48.png" alt="Nx logo" width="40"><sub>Nx</sub></a></td><td align="center" width="200px"><a target="_blank" href="https://github.com/element-plus/element-plus"><img src="https://user-images.githubusercontent.com/40693636/172459748-939e3f1b-a694-4c09-b643-e1dce602105c.png" alt="Element Plus logo" width="40"><sub>Element Plus</sub></a></td><td align="center" width="200px"><a target="_blank" href="https://github.com/Tencent/tdesign-vue-next"><img src="https://user-images.githubusercontent.com/40693636/170830562-38e4c998-9af4-4303-9270-4f14e0942b08.png" alt="TDesign-Vue-Next logo" width="40"><sub>TDesign-Vue-Next</sub></a></td><td align="center" width="200px"><a target="_blank" href="https://github.com/vbenjs/vue-vben-admin"><img src="https://user-images.githubusercontent.com/40693636/178189964-931a1fc2-92df-4d04-8d0d-b748fc318c0a.png" alt="Vben-Admin logo" width="40"><sub>Vben-Admin</sub></a></td></tr></table><h2 id="license" tabindex="-1">LICENSE <a class="header-anchor" href="#license" aria-hidden="true">#</a></h2><p>MIT Copyright (c) 2022-present Qiubin Zheng <a href="mailto:zhengqbbb@gmail.com" target="_blank" rel="noreferrer">zhengqbbb@gmail.com</a> (<a href="https://github.com/Zhengqbbb" target="_blank" rel="noreferrer">https://github.com/Zhengqbbb</a>)</p><blockquote><p>I just do my best to make thing well, Could you give a <a href="https://github.com/Zhengqbbb/cz-git" target="_blank" rel="noreferrer">star ⭐</a> to encourage me ?</p></blockquote></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("en/api/index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
